import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'

import Stack from '../components/chart/stack'

import Card from '@mui/material/Card'
import CardActions from '@mui/material/CardActions'
import CardContent from '@mui/material/CardContent'
import Button from '@mui/material/Button'
import Typography from '@mui/material/Typography'

const DataStructures: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Data Structures</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='dataStructures'>
                <h3 className='header'>Data Structures</h3>
                <Navigation />
                <Card className="card">
                    <Stack />
                </Card>
            </main>
        </div>
    )
}

export default DataStructures
