import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'

import Stack from '../components/chart/stack'

const DataStructures: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Data Structures</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='dataStructures'>
                <h3 className='header'>Data Structures</h3>
                <Navigation />
                <Stack />
            </main>
        </div>
    )
}

export default DataStructures
