import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'

import HashtableComponent from '../components/chart/hashtable'

const Hashtable: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Hashtable</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='hashtable'>
                <h3 className='header'>Hashtable</h3>
                <Navigation />
                <HashtableComponent />
            </main>
        </div>
    )
}

export default Hashtable
