import type { NextPage } from 'next'
import Navigation from '../components/navigation'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='home'>
        <h3 className='header'>Hello World</h3>
        <Navigation/>
      </main>
    </div>
  )
}

export default Home
