import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'

import Stack from '../components/chart/stack'
import Queue from '../components/chart/queue'

const StackQueue: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Stack and Queue</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='stackqueue'>
                <h3 className='header'>Data Structures</h3>
                <Navigation />
                <div className="stack_queue">
                    <Stack />
                    <Queue />
                </div>
            </main>
        </div>
    )
}

export default StackQueue
