import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'
import Navigation from '../components/navigation'
import Card from '@mui/material/Card'

const Tree = dynamic(() => import('react-d3-tree'), {
    ssr: false,
})

const orgChart = {
    name: 'CEO',
    children: [
      {
        name: 'Manager',
        attributes: {
          department: 'Production',
        },
        children: [
          {
            name: 'Foreman',
            attributes: {
              department: 'Fabrication',
            },
            children: [
              {
                name: 'Worker',
              },
            ],
          },
          {
            name: 'Foreman',
            attributes: {
              department: 'Assembly',
            },
            children: [
              {
                name: 'Worker',
              },
            ],
          },
        ],
      },
    ],
  }

const Trie: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Tree</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='trie'>
                <h3 className='header'>Tree</h3>
                <Navigation />
                <Card className="tree-card">
                    <Tree data={orgChart} orientation="vertical" pathFunc={'step'} translate={{ x:450, y: 50 }}/>
                </Card>
            </main>
        </div>
    )
}

export default Trie

//https://www.youtube.com/watch?v=Kpz4Ro5iD1Q