import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useState } from 'react'
import Navigation from '../components/navigation'
import Card from '@mui/material/Card'
import TreeRender from '../components/tree/tree-render'

const Tree = dynamic(() => import('react-d3-tree'), {
    ssr: false,
})

interface treeObject {
  name: string,
  children: Array<any>
}

const starterTree = {
  name: 'StarterNode',
  children: []
}

const Trie: NextPage = () => {
    const [treeData, setTreeData] = useState<treeObject>(starterTree)
    const [nodeList, setNodeList] = useState<Array<string>>([])
    return (
        <div>
            <Head>
                <title>Tree</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='trie'>
                <h3 className='header'>Tree</h3>
                <Navigation />
                <div className="tree-card_functions">
                  <Card className="tree-card">
                      <Tree data={treeData} orientation="vertical" pathFunc={'straight'} translate={{ x:450, y: 50 }} nodeSize={{x: 80, y: 70}}/>
                  </Card>
                  <TreeRender treeData={treeData} setTreeData={setTreeData} nodeList={nodeList} setNodeList={setNodeList}/>
                </div>
            </main>
        </div>
    )
}

export default Trie

//https://www.youtube.com/watch?v=Kpz4Ro5iD1Q